### ISSUE TITLE
Would it be possible to add macaque standards?

### ISSUE THREAD

**Issue by JianxunRen** [recoveringyank/precon_all#1]
Thanks for sharing this amazing tool! It's very helpful for researchers who are struggling with animal surface recon. I just noticed in there is a macaque surface in your poster, however, the repo only includes the standards for pig. So would it be possible to add macaque standards?

**Comment by recoveringyank** [comment]
absolutely!

**Comment by recoveringyank** [comment]
Hey! I'll try to upload the masks etc... this week or next week. we used the NIMH macaque template, and it's what we'll include as the standard template here.  I do need to add a few more hacks to get around segmentation issues of the blood vessels in the macaque, a problem we don't have with pigs.

**Comment by recoveringyank** [comment]
Hi Y'all, the files for the NMT template from NIMH (paper here: https://www.ncbi.nlm.nih.gov/pmc/articles/pmid/28461058/) are now uploaded. I recommend using > 80 GB of memory when running it, as the template is very high resolution and fnirt needs the memory. I may downsample the template in future versions to make it less computationally intensive to run.
